Publish topics using friendly_name and not IP
nohum/chromecast-mqtt-connector pull request #8
Opened 2017-08-12 16:59 UTC by berryk

Publishes topics using friendly_name and not IP. 

This also resolves #3 support for audio groups.

2017-08-13 19:16 UTC, nohum requested changes

2017-08-13 19:16 UTC, nohum commented on README.md
> +You can install the requirements in their correct versions using `pfriendly_name3 install -r requirements.txt`.
Seems like a small typo to me ;)

2017-08-13 19:17 UTC, nohum commented
Nice, thanks! I will give it a try today or tomorrow, but just by looking at the code this looks promising 👍

2017-08-14 02:11 UTC, berryk commented on README.md
> +You can install the requirements in their correct versions using `pfriendly_name3 install -r requirements.txt`.
Yes - well spotted, search and replace error. Sorry!

2017-08-14 02:14 UTC, berryk reviewed
Fixed the typo

2017-08-15 18:03 UTC, nohum approved these changes

2017-08-15 18:44 UTC, nohum commented
Tested it and works like a charm. Thanks!

2017-08-15 18:45 UTC, merged